ci(default-crossaction): netbsd as experimental
```
Collecting rpds-py>=0.7.1 (from jsonschema>=4.9.1->molecule)
  Downloading rpds_py-0.25.1.tar.gz (27 kB)
[...]
        Downloaded rpds v1.1.1
      error: failed to parse manifest at
`/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rpds-1.1.1/Cargo.toml`

      Caused by:
        feature `edition2024` is required

        The package requires the Cargo feature called `edition2024`, but
that feature is not stabilized in this version of Cargo (1.83.0
(5ffbef321 2024-10-29)).
        Consider trying a newer version of Cargo (this may require the
nightly release).
        See
https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024
for more information about the status of this feature.
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with
`cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517',
'write-dist-info', '--metadata-directory',
'/tmp/pip-modern-metadata-6qlszmca', '--interpreter',
'/usr/pkg/bin/python3.11']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory
/tmp/pip-modern-metadata-6qlszmca --interpreter /usr/pkg/bin/python3.11`
      [end of output]
```